### ISSUE TITLE
matchExt doesn't match files in subfolders

### ISSUE THREAD

**Issue by dbarrosop** [numtide/nix-filter#29]
**Describe the bug**

If I do:

```
        nix-src = nix-filter.lib.filter {
          root = ./.;
        };
```

I can see all the files, subfolders, files in subfolders, etc, being matched correctly. However, if I do:

```
        nix-src = nix-filter.lib.filter {
          root = ./.;
          include = with nix-filter.lib;[
             (matchExt "nix")
          ];
        };
```

I only see the `*.nix` files in the root folder being matched, none of the files with that extension in subfolders is matched at all.

**To Reproduce**

See above.

**Expected behavior**

Files with the specified extension in subfolders that would be matched otherwise should be matched too.

**System information**

Using commit 825abbb40ed6b1e5e5fce95e2c21a1f5881ecf61

**Additional context**

N/A

**Comment by zimbatm** [comment]
As soon as one include is being defined, the filter will only allow those. To also add directories, add `isDirectory` to the list.

**Comment by dbarrosop** [comment]
So if you have the files:

- `flake.nix`
- `folder/some.nix`
- `folder/something_else.txt`
- `folder/....`
- `...`

There is no way to just include all nix files ignoring the rest?

**Comment by zimbatm** [comment]
This project depends on the nix `builtins.path`, which doesn't allow recursing into directories without adding them to the store. So either add them all using isDirectory, or explicitly list all the directories you want to have added.

        nix-src = nix-filter.lib.filter {
          root = ./.;
          include = with nix-filter.lib;[
             isDirectory
             (matchExt "nix")
          ];
        };

**Comment by dbarrosop** [comment]
ok, thanks for the help. Does this change with #27? Might also be worth adding as an example in the `README.md` as requiring the `isDirectory` is a bit counterintuitive (or maybe rename/alias as `Recursive`?).

Thanks again :)

**Comment by zimbatm** [comment]
#27 makes one use-case a bit better: if you list ./foo/bar.txt as an include, it automatically adds the ./foo directory. Before you had to explicitly target both.
