### ISSUE TITLE
matchExt never matches top-level files

### ISSUE THREAD

**Issue by DavHau** [numtide/nix-filter#41]
**Describe the bug**

**To Reproduce**

1. setup filter:
```
nix-filter {
    # ...
    exclude = [
      (nix-filter.matchExt ".nix")
    ];
};
```

2. add a new line to the flake.nix
3. notice that a rebuilt of the package is triggered

**Expected behavior**
Adding a new line to the flake.nix should not trigger a re-build

**System information**

**Additional context**

**Comment by zimbatm** [comment]
Try without the `.` ;)

`(nix-filter.matchExt "nix")`

**Comment by DavHau** [comment]
Hm but with the `.` it still seems to match for files in sub-directories, in which case this would be an inconsistency.

**Comment by DavHau** [comment]
While making a minimal reproducer I noticed my assumption was wrong. `(nix-filter.matchExt ".nix")` does not filer anything at all.
Sorry for that.
